$schema: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
console_title_template: "{{ .Folder }}"
version: 4
var:
  CpuCores: 8.0
palettes:
  template: "{{ if .Root }}root{{ else }}default{{ end }}"
  list:
    default:
      fg: "#011627"
      bg: "#FEF5ED"
    root:
      fg: "#FEF5ED"
      bg: "#c40707"
blocks:
  - alignment: left
    newline: true
    type: prompt
    segments:
      - background: p:bg
        foreground: p:fg
        leading_diamond: ""
        style: diamond
        template: "{{ if .WSL }}WSL at {{ end }}{{.Icon}} {{.UserName}}@{{.HostName}} "
        trailing_diamond: <transparent,p:bg></>
        type: os
        options:
          macos: ""
          ubuntu: " "
          windows: " "
      - background: "#FEF5ED"
        foreground: "#011627"
        leading_diamond: 
        style: diamond
        template: " {{ if .SSHSession }}󰢹 {{ else }} {{ end }}{{ .Shell }} "
        trailing_diamond: <transparent,#FEF5ED></>
        type: session
      - background: "#516BEB"
        foreground: "#ffffff"
        leading_diamond: 
        style: diamond
        template: "   {{ round .PhysicalPercentUsed 0 }}% |   {{ round (min 100 (mulf (divf 100.0 .Var.CpuCores) .Load1)) .Precision }}% "
        trailing_diamond: <transparent,#516BEB></>
        type: sysinfo
      - background: "#575656"
        foreground: "#d6deeb"
        leading_diamond: 
        style: diamond
        template: " {{ .FormattedMs }} "
        trailing_diamond: 
        type: executiontime
        options:
          style: roundrock
          threshold: 0
  - alignment: right
    type: prompt
    segments:
      - background: "#17D7A0"
        foreground: "#011627"
        leading_diamond: 
        style: diamond
        template: "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus
          }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end
          }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if
          .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt
          .StashCount 0 }}  {{ .StashCount }}{{ end }}"
        trailing_diamond: 
        type: git
        options:
          branch_icon: "  "
          tag_icon: " "
          fetch_status: true
          fetch_upstream_icon: true
  - alignment: left
    newline: true
    type: prompt
    segments:
      - style: plain
        template: ╭─
        type: text
      - style: plain
        template: " {{ .CurrentDate | date .Format }} "
        type: time
        options:
          time_format: 15:04
      # - style: plain
      #   template: "  "
      #   type: root
      - style: plain
        template: "{{ .Path }}"
        type: path
        options:
          style: agnoster_full
        #   # folder_icon: " / "
        #   folder_separator_icon: "  "
        #   home_icon: " "
  - alignment: left
    newline: true
    type: prompt
    segments:
      - style: plain
        template: "╰─ "
        type: status
        options:
          always_enabled: true
transient_prompt:
  background: transparent
  foreground: "#FEF5ED"
  template: " "
