---
$schema: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
  - alignment: left
    newline: true
    segments:
      - background: p:bg
        foreground: p:fg
        leading_diamond: 
        options:
          macos: 
          ubuntu: ' '
          windows: ' '
        style: diamond
        template: '{{ if .WSL }}WSL at {{ end }}{{.Icon}} {{.UserName}}@{{.HostName}} '
        trailing_diamond: <transparent,p:bg></>
        type: os
      - background: '#FEF5ED'
        foreground: '#011627'
        leading_diamond: 
        style: diamond
        template: ' {{ if .SSHSession }} {{ if .Root }}0 {{ end }}{{ .Shell }} '
        trailing_diamond: <transparent,#FEF5ED></>
        type: session
      - background: '#516BEB'
        foreground: '#ffffff'
        leading_diamond: 
        style: diamond
        template: '   {{ round .PhysicalPercentUsed 0 }}% |   {{ round (min 100 (mulf (divf 100.0 .Var.CpuCores) .Load1)) .Precision }}% '
        trailing_diamond: <transparent,#516BEB></>
        type: sysinfo
      - background: '#575656'
        foreground: '#d6deeb'
        leading_diamond: 
        options:
          style: roundrock
          threshold: 0
        style: diamond
        template: ' {{ .FormattedMs }} '
        trailing_diamond: 
        type: executiontime
    type: prompt
  - alignment: right
    segments:
      - background: '#17D7A0'
        foreground: '#011627'
        leading_diamond: 
        options:
          branch_icon: '  '
          fetch_status: true
          fetch_upstream_icon: true
          tag_icon: ' '
        style: diamond
        template: {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus
          }}{{ else }}0{{ if .Working.Changed }}  {{ .Working.String }}{{ end
          }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if
          .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt
          .StashCount 0 }}  {{ end }}0{{ end }}
        trailing_diamond: 
        type: git
    type: prompt
  - alignment: left
    newline: true
    segments:
      # - style: plain
      #   template: "  "
      #   type: root
      - style: plain
        template: ╭─
        type: text
      - options:
          time_format: '15:04'
        style: plain
        template: ' {{ .CurrentDate | date .Format }} '
        type: time
      - options:
          style: agnoster_full
        style: plain
        template: {{ .Path }}
        type: path
    type: prompt
        #   # folder_icon: " / "
        #   folder_separator_icon: "  "
        #   home_icon: " "
  - alignment: left
    newline: true
    segments:
      - options:
          always_enabled: true
        style: plain
        template: '╰─ '
        type: status
    type: prompt
console_title_template: {{ .Folder }}
palettes:
  list:
    default:
      bg: '#FEF5ED'
      fg: '#011627'
    root:
      bg: '#970000'
      fg: '#FEF5ED'
  template: vscode-yaml-sort.helm.1rootvscode-yaml-sort.helm.2defaultvscode-yaml-sort.helm.3
transient_prompt:
  background: transparent
  foreground: '#FEF5ED'
  template: ' '
var:
  CpuCores: 8
version: 4